console.log("🚀 Setting up Swarms Status Monitor for local development")
console.log("")
console.log("Prerequisites:")
console.log("1. Node.js 18+ installed")
console.log("2. Next.js project structure")
console.log("3. Supabase account (optional for data persistence)")
console.log("4. Required packages: npm install @vercel/edge-config")
console.log("")
console.log("Environment Variables:")
console.log("")
console.log("Required:")
console.log("SWARMS_API_KEY=your_swarms_api_key_here")
console.log("")
console.log("Optional (for data persistence):")
console.log("NEXT_PUBLIC_SUPABASE_URL=your_supabase_project_url")
console.log("NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key")
console.log("SUPABASE_SERVICE_ROLE_KEY=your_supabase_service_role_key")
console.log("")
console.log("To start development:")
console.log("1. Create .env.local with the environment variables above")
console.log("2. Run: npm install")
console.log("3. Run: npm run dev")
console.log("4. Visit: http://localhost:3000")
console.log("")
console.log("Features:")
console.log("- Real-time status monitoring")
console.log("- Historical data tracking (if Supabase configured)")
console.log("- Incident management")
console.log("- Performance metrics")
console.log("- API health checks")
console.log("")
