name: Monitor Swarms API

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Monitor API
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOYMENT_URL }}/api/monitor" \
            -H "Authorization: Bearer ${{ secrets.MONITORING_CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --fail-with-body || echo "Monitoring request failed"
